### ISSUE TITLE
返回数据 【建议】

### ISSUE THREAD

**Issue by luoqiz** [wangdingfeng/spark-platform#1]
建议将返回数据做统一包装，不要指定返回数据结构确定为 ApiResponse,这样swagger上也更能使前端看到真正的数据格式，后台自己看的也更清楚明白。

**Comment by wangdingfeng** [comment]
感谢您的建议，当时我在写的时候光顾着入参，出参确实没有注意到。这个会在下个大版本中迭代更新。再次感谢您的建议，希望您多多建议

**Comment by luoqiz** [comment]
客气啦，我也是自己项目中出现过这个问题。大致看了一下这个项目源码，碰巧了。哈哈
