### ISSUE TITLE
工作流cms问题的思路请教

### ISSUE THREAD

**Issue by arraycto** [wangdingfeng/spark-platform#10]
大佬您好。麻烦大佬提供一下思路即可，自己没想通，非常感谢。如下：
背景：按照您给的文章审核工作流没有问题，流程通的，已经本地测试。
问题：如果更改了业务流程，
```
如情况1（在文章流程基础上进行改动和微调）：
文章发布-组长审核-主编1-专家审核-结束，这种情况除了更改bpm20.xml那个设计图外还需要更改cms的代码？
```

```
如情况2（在文章流程的基础上进行删减，原流程主线条一致）：
文章发布-组长审核-结束，这种情况除了更改bpm20.xml那个设计图外，代码是不需要更改的，直接可以用？还是也需要对应新的流程进行更改？
```

```
如情况3（完全不同文章审核流程）：
财务审核-运营审核-经理审核-结束，这种情况除了更改bpm20.xml那个设计图外还需要更改cms的代码？
```

**Comment by wangdingfeng** [comment]
你说的三种情况，代码是一定要改的，流程图变化，代码也要变化，因为你的流程图中网关中的变量变化了，还有每个节点执行的业务逻辑是不一样的，所以流程图变化，基本就意味着你的代码也要变化。我的那个文章审核流程只是提供了一个简单的，并行节点、如何进行流程推进的例子。无论你流程图如何变化，只要你在你对应的节点走对应的路线，那就没有问题。你可以去看下网管后边的每条线，都是有变量表达式来控制我要走那条线

**Comment by arraycto** [comment]
非常感谢您的思路和指点~ 
请问有没有那种通用型的或者微调的类型的解决方案（思路）。
实际业务场景：集团公司工作流A，分公司在工作流A的基础上需要工作流A1 （变动工作流A基础上+2审核流程），子公司也是在集团工作流A的基础上简化工作流程（工作流A2，A的精简版）。如果针对一个saas系统（集团公司+众多分公司+众多子公司）来说，一个工作流A（固定模式的）不能满足.。工作流A和A1，A2既有关系又无关系。这种是不是要做三套bpm20.xml（或者N套流程），并非一套工作流A进行动态规划？如果动态可配置，请问有思路或者方向么？
难点：一旦后台或者管理者更改流程，意味着旧代码不可用，新代码还要开发，客户要求所见即所得~
再次感谢大佬指点一下思路和研究方向即可。跪谢~

**Comment by wangdingfeng** [comment]
你这种情况的话就要划一个完整的流程图，把所有的流程节点都画上，然后后台控住你那个公司要走那几个节点，其他的借节点自动跳过就好了

**Comment by arraycto** [comment]
哇，明白，非常感谢，大拇指赞

**Comment by wangdingfeng** [comment]
我刚建了一个群，你可以加群了

**Comment by arraycto** [comment]
支持支持，已请求，也欢迎看见issues的小伙伴们添加群。spark学到了很多知识。感谢大佬。
