### ISSUE TITLE
IE兼容性问题，Vue官方是支持IE高版本的

### ISSUE THREAD

**Issue by arraycto** [wangdingfeng/spark-platform#11]
大佬您好：
 测试问题：IE兼容性问题
IE版本：IE11
现状：白屏，无登录页面，登录页面显示白屏
复现：www.sparkplaform.cn官网首页

解决方案：
    Vue支持高版本的IE的哦，希望大佬修复bug，供参考。

IE在企业中还是有些用户的，尤其是一部分领导没安装现代浏览器。供参考哈。

**Comment by wangdingfeng** [comment]
前期由于我的电脑是mac系统没有IE，所以没测试过。我后边找一下问题，处理一下

**Comment by arraycto** [comment]
Thanks♪(･ω･)ﾉ大佬回复。为了软件的长远发展，兼容性属于关键。供参考。

**Comment by wangdingfeng** [comment]
更新spark-admin代码,重新install 就可以了

**Comment by arraycto** [comment]
niuiniu 牛
