### ISSUE TITLE
项目占用内存过大，求指导

### ISSUE THREAD

**Issue by arraycto** [wangdingfeng/spark-platform#12]
测试主机：win10
内存：16G
型号：Tinkpad T480 

ide：
后端：idea 2019.1.3
前端：vscode 1.x.50.x （2020年10月11日最新版本）

**bug或者待优化现象：**
1.通过idea启动整个项目后（内存占81%）
2.启动vscode后，执行npm run dev 后打开谷歌浏览器，出现oom，内存不足，浏览器奔溃
3.修正或者编辑vscode中的代码时 vscode出现oom的错误。
截图见下方：

**问题：**
 1） 请问大佬，这种情况属于代码的某一个小问题还是属于idea或者vscode设置不当？
   纠结的地方是即使项目勉强跑起来了，一更改代码，系统卡死或者oom，浏览器无法使用，这种影响开发。同事们的电脑都是8G的。是不是该项目本身要求电脑的配置就需要很高，需要32G？
![oom](https://user-images.githubusercontent.com/37463247/95671014-c7e37400-0bc4-11eb-95c4-670ed95805a6.png)

 2）请问大佬的开发机的配置？

**Comment by wangdingfeng** [comment]
MAC: 8G内存。
后端开发工具:IDEA 2019.3
前端开发工具: vscode 1.41
浏览器： Chrome 86.0.4240.75
NACOS、REDIS 不在本机运行。
gateway、auth、admin、flowable、cms启动。前端服务器启动。
内存占用确实会达到80%以上，但是并没有出现浏览器崩溃的情况。
建议：只要是采用分布式微服务开发的都是很耗内存的,8G内存是不够用的，这个项目建议最少是16G内存开发。建议修改每个微服务中java的jvm值。
线上服务器的配置：
2台1核2G1M带宽的服务器 运行后台系统 
1台服务器运行这Nacos、mysql、redis 
1台服务器运行着前端项目和control项目

**Comment by arraycto** [comment]
非常感谢大佬详细的解答。
