### ISSUE TITLE
权限控制【bug】

### ISSUE THREAD

**Issue by luoqiz** [wangdingfeng/spark-platform#5]
现象：前端页面在使用admin用户登录查看多个功能模块后，在使用其它用户登录后，admin查看的模块仍然存在导航栏。最致命的是这些没有权限的功能模块仍然可以操作。

**Comment by wangdingfeng** [comment]
这个问题会在近期修改，Thanks♪(･ω･)ﾉ

**Comment by wangdingfeng** [comment]
问题已修复，更新spark-admin代码

**Comment by wangdingfeng** [comment]
问题已修复，更新spark-admin代码
