### ISSUE TITLE
文章审核流程，待办无记录问题

### ISSUE THREAD

**Issue by arraycto** [wangdingfeng/spark-platform#7]
bug：组长身份，待办无记录

重现：大佬，您好，下载例子中的文章审核流程图，流程图发布，admin发布文章，组长审核阶段，新创建一个组长用户或者使用zuzhang用户，待办无待审核的文章记录，请问是我操作不对还是bug
浏览器：谷歌，火狐

说明：请问操作上有无限制么，还是bug，感谢大佬指点。

**Comment by arraycto** [comment]
测试1：待办记录，本地127.0.0.1有问题
测试2：在线的www.sparkplatform.cn无问题

使用的是：从www.sparkplatform.cn下载的bpm20.xml导入的
原因：找了一周无果
错误类型：后台不报任何错误

**Comment by wangdingfeng** [comment]
因为以前的角色code是小写的，你现在在拉取一下代码，用新的流程图。新的流程图组长审核角色是大写的，跟系统中角色的code就对上了

**Comment by arraycto** [comment]
可能sql旧版的原因，sql中还是小写的。代码已经是最新，准备请问我手动更改sys_role的小写为大写是否就可以了。

**Comment by wangdingfeng** [comment]
抱歉，这个sql中没有更新，你把sys_role 改成大写的吧，然后流程图你更新到最新的那个，就可以了

**Comment by arraycto** [comment]
搞定。感谢感谢
