### ISSUE TITLE
【bug】工作流发布功能，供参考哈，莫见怪

### ISSUE THREAD

**Issue by arraycto** [wangdingfeng/spark-platform#8]
场景：
bug场景：点击列表的发布按钮，表面上发布成功，一刷新变成【暂存】非发布成功,  发布后直接刷新看状态
     
![image](https://user-images.githubusercontent.com/37463247/92206160-b6b69180-eeb9-11ea-9e2e-6f003e826dc4.png)

正常场景：
![image](https://user-images.githubusercontent.com/37463247/92206326-e82f5d00-eeb9-11ea-894f-7de62dab45eb.png)

**Comment by wangdingfeng** [comment]
这个文章审核当时只是为了提供一个工作流测试，所以当时写的时候跟多bug就没仔细去改，后续我该一下吧。没事，我巴不得你们多提点建议了

**Comment by arraycto** [comment]
期待期待，更多工作流的例子和功能。

**Comment by wangdingfeng** [comment]
工作流的话，后续应该不会太多的例子了，这个例子基本把大部分要用到的都给展示了一下，如果有你们特殊的需求的，可以给我提个issues，我可以帮忙看下。后续工作流会着重邮件和钉钉通知，至于流程引擎中的表单引擎，我这边都没有用，我们大部分的需求的表单都是很复杂的，表单引擎不方便，所以就没用

**Comment by arraycto** [comment]
明白明白，非常感谢。这个issues关闭了。后续有问题开心的issues向大佬请教。
