### ISSUE TITLE
【bug】流程的时间格式不对NaN，，供参考哈，莫见怪

### ISSUE THREAD

**Issue by arraycto** [wangdingfeng/spark-platform#9]
大佬您好，在使用过程中出现这个NaN,供参考哈。不是有意提bug，供参考，再次感谢大佬的学习源泉。
![image](https://user-images.githubusercontent.com/37463247/92206572-52480200-eeba-11ea-91bd-1c9cca528572.png)

**Comment by wangdingfeng** [comment]
这个一般都是时间格式不正确导致，你看一下列表请求回来的参数。或者在更新一下代码，是不是代码没更新，现在线上的代码应该是最新的，没有问题的

**Comment by arraycto** [comment]
代码是最新的。我再clean一下看看。感谢
